### PR TITLE
[>=2.3.0] xmlwf: Fix a memory leak on output file opening error (fixes #544)

### LINKED ISSUE #544: [>=2.3.0] xmlwf: Memory leak on output file opening error
In file xmlwf.c line 1179, need to call `free(outName);` out of if condition, no matter it's continueOnError or not. Otherwise there is risk of memory leak.

### PR DESCRIPTION
**Pull request by hartwork**
Fixes issue #544 

Related to pull request #439

CC @hwt0415 @timbray

### CODE REVIEW

File: expat/xmlwf/xmlwf.c [hunk 1]
```diff
@@ -1175,8 +1175,9 @@ tmain(int argc, XML_Char **argv) {
       if (! userData.fp) {
         tperror(outName);
         exitCode = XMLWF_EXIT_OUTPUT_ERROR;
+        free(outName);
```
Comment (timbray) [inline expat/xmlwf/xmlwf.c:1178]: Heh, pretty obvious when you look at it, there was no reason to have the free only in the -k case.

**Review by timbray — APPROVED** [review]

File: expat/xmlwf/xmlwf.c (hunk 1 above)
Comment (hartwork) [reply expat/xmlwf/xmlwf.c:1178]: @timbray thanks for having a look!

I noticed now that the call to `cleanupUserData(&userData)` should either be moved out of the conditional or be dropped altogether. Keeping and moving seems more robust towards the future, but either approach seems to be valid. What do you think?

CC @hwt0415

Comment (hartwork) [reply expat/xmlwf/xmlwf.c:1178]: I thought about this again. There is no chance that we have information about the doctype or notations (derived from from file content) this early in the process for each file. I have dropped the call to `cleanupUserData(&userData)` as a result.
